<?php

namespace Database\Seeders;

use App\Models\Paciente;
use App\Models\Sucursal;
use Illuminate\Database\Seeder;

class PacienteSeeder extends Seeder
{
    public function run(): void
    {
        $sucursalCentral = Sucursal::where('codigo_sucursal', 'SUC-001')->first();
        $sucursalNorte = Sucursal::where('codigo_sucursal', 'SUC-002')->first();

        $pacientesData = [
            // Sucursal Central (5 pacientes)
            [
                'codigo_paciente' => 'PAC-001',
                'sucursal_id' => $sucursalCentral?->id,
                'nombre' => 'Juan',
                'apellido' => 'Pérez',
                'edad' => 34,
                'sexo' => 'Masculino',
                'ocupacion' => 'Ingeniero de Sistemas',
                'estado_civil' => 'Soltero',
                'celular' => '76543210',
                'domicilio_actual' => 'Av. Arce 1234, Sopocachi',
                'fecha_nacimiento' => '1992-05-15',
                'telefono_emergencia' => '71112233',
                'nombre_contacto_emergencia' => 'María',
                'apellido_contacto_emergencia' => 'Pérez',
                'parentesco_contacto_emergencia' => 'Hermana',
            ],
            [
                'codigo_paciente' => 'PAC-002',
                'sucursal_id' => $sucursalCentral?->id,
                'nombre' => 'Lucía',
                'apellido' => 'Fernández',
                'edad' => 28,
                'sexo' => 'Femenino',
                'ocupacion' => 'Diseñadora Gráfica',
                'estado_civil' => 'Soltera',
                'celular' => '77665544',
                'domicilio_actual' => 'Calle 15 de Calacoto #45',
                'fecha_nacimiento' => '1998-08-20',
                'telefono_emergencia' => '72223344',
                'nombre_contacto_emergencia' => 'Carlos',
                'apellido_contacto_emergencia' => 'Fernández',
                'parentesco_contacto_emergencia' => 'Padre',
            ],
            [
                'codigo_paciente' => 'PAC-003',
                'sucursal_id' => $sucursalCentral?->id,
                'nombre' => 'Roberto',
                'apellido' => 'Gómez',
                'edad' => 45,
                'sexo' => 'Masculino',
                'ocupacion' => 'Contador Auditor',
                'estado_civil' => 'Casado',
                'celular' => '71223344',
                'domicilio_actual' => 'Av. 6 de Agosto #890',
                'fecha_nacimiento' => '1981-11-03',
                'telefono_emergencia' => '73334455',
                'nombre_contacto_emergencia' => 'Elena',
                'apellido_contacto_emergencia' => 'Gómez',
                'parentesco_contacto_emergencia' => 'Esposa',
            ],
            [
                'codigo_paciente' => 'PAC-004',
                'sucursal_id' => $sucursalCentral?->id,
                'nombre' => 'Sofía',
                'apellido' => 'Morales',
                'edad' => 22,
                'sexo' => 'Femenino',
                'ocupacion' => 'Estudiante Universitaria',
                'estado_civil' => 'Soltera',
                'celular' => '78889900',
                'domicilio_actual' => 'Calle Murillo #321',
                'fecha_nacimiento' => '2004-03-12',
                'telefono_emergencia' => '74445566',
                'nombre_contacto_emergencia' => 'Patricia',
                'apellido_contacto_emergencia' => 'Morales',
                'parentesco_contacto_emergencia' => 'Madre',
            ],
            [
                'codigo_paciente' => 'PAC-005',
                'sucursal_id' => $sucursalCentral?->id,
                'nombre' => 'Miguel',
                'apellido' => 'Torres',
                'edad' => 52,
                'sexo' => 'Masculino',
                'ocupacion' => 'Arquitecto',
                'estado_civil' => 'Casado',
                'celular' => '79990011',
                'domicilio_actual' => 'Av. Ballivián #567, Calacoto',
                'fecha_nacimiento' => '1974-09-25',
                'telefono_emergencia' => '75556677',
                'nombre_contacto_emergencia' => 'Carmen',
                'apellido_contacto_emergencia' => 'Torres',
                'parentesco_contacto_emergencia' => 'Esposa',
            ],

            // Sucursal Norte (5 pacientes)
            [
                'codigo_paciente' => 'PAC-006',
                'sucursal_id' => $sucursalNorte?->id,
                'nombre' => 'Camila',
                'apellido' => 'Rojas',
                'edad' => 31,
                'sexo' => 'Femenino',
                'ocupacion' => 'Abogada',
                'estado_civil' => 'Soltera',
                'celular' => '70001122',
                'domicilio_actual' => 'Calle América #102, Zona Norte',
                'fecha_nacimiento' => '1995-01-30',
                'telefono_emergencia' => '76667788',
                'nombre_contacto_emergencia' => 'Jorge',
                'apellido_contacto_emergencia' => 'Rojas',
                'parentesco_contacto_emergencia' => 'Hermano',
            ],
            [
                'codigo_paciente' => 'PAC-007',
                'sucursal_id' => $sucursalNorte?->id,
                'nombre' => 'Diego',
                'apellido' => 'Vargas',
                'edad' => 39,
                'sexo' => 'Masculino',
                'ocupacion' => 'Administrador de Empresas',
                'estado_civil' => 'Casado',
                'celular' => '71110022',
                'domicilio_actual' => 'Av. Panamericana #432',
                'fecha_nacimiento' => '1987-07-18',
                'telefono_emergencia' => '77778899',
                'nombre_contacto_emergencia' => 'Valeria',
                'apellido_contacto_emergencia' => 'Vargas',
                'parentesco_contacto_emergencia' => 'Esposa',
            ],
            [
                'codigo_paciente' => 'PAC-008',
                'sucursal_id' => $sucursalNorte?->id,
                'nombre' => 'Andrea',
                'apellido' => 'Mendoza',
                'edad' => 26,
                'sexo' => 'Femenino',
                'ocupacion' => 'Médico General',
                'estado_civil' => 'Soltera',
                'celular' => '72221133',
                'domicilio_actual' => 'Calle España #654',
                'fecha_nacimiento' => '2000-10-05',
                'telefono_emergencia' => '78889900',
                'nombre_contacto_emergencia' => 'Fernando',
                'apellido_contacto_emergencia' => 'Mendoza',
                'parentesco_contacto_emergencia' => 'Padre',
            ],
            [
                'codigo_paciente' => 'PAC-009',
                'sucursal_id' => $sucursalNorte?->id,
                'nombre' => 'Gabriel',
                'apellido' => 'Castro',
                'edad' => 48,
                'sexo' => 'Masculino',
                'ocupacion' => 'Comerciante',
                'estado_civil' => 'Casado',
                'celular' => '73332244',
                'domicilio_actual' => 'Av. Juan de la Riva #876',
                'fecha_nacimiento' => '1978-04-08',
                'telefono_emergencia' => '79990011',
                'nombre_contacto_emergencia' => 'Rosa',
                'apellido_contacto_emergencia' => 'Castro',
                'parentesco_contacto_emergencia' => 'Esposa',
            ],
            [
                'codigo_paciente' => 'PAC-010',
                'sucursal_id' => $sucursalNorte?->id,
                'nombre' => 'Mariana',
                'apellido' => 'Ortiz',
                'edad' => 29,
                'sexo' => 'Femenino',
                'ocupacion' => 'Comunicadora Social',
                'estado_civil' => 'Soltera',
                'celular' => '74443355',
                'domicilio_actual' => 'Calle Illimani #210',
                'fecha_nacimiento' => '1997-12-14',
                'telefono_emergencia' => '70001122',
                'nombre_contacto_emergencia' => 'Esteban',
                'apellido_contacto_emergencia' => 'Ortiz',
                'parentesco_contacto_emergencia' => 'Hermano',
            ],
        ];

        foreach ($pacientesData as $data) {
            Paciente::firstOrCreate(
                ['codigo_paciente' => $data['codigo_paciente']],
                $data
            );
        }
    }
}
