# ETAPA 1: Construir el frontend estático
FROM node:20-alpine as build
WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm ci

# Copiar el código fuente y construir
COPY . .
# En este punto se leerán las variables de entorno de producción
RUN npm run build

# ETAPA 2: Servidor Web (Nginx) para despachar la SPA
FROM nginx:alpine
# Copiar el build compilado
COPY --from=build /app/dist /usr/share/nginx/html
# Copiar la configuración que evita errores 404
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
