server {
    listen 80;

    # Directorio donde Vite genera los estáticos
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Cualquier ruta que no sea un archivo real, redirige al index.html
    # Esto soluciona los errores 404 al recargar páginas en React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desactivar caché para el HTML principal (siempre cargar última versión)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Configurar caché para assets estáticos
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
